version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: fncc-trckr-db
    environment:
      POSTGRES_DB: fncc-trckr
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: